# Changes here will be overwritten by Copier
_commit: 5af64c5
_src_path: https://github.com/python-project-templates/base.git
add_docs: true
add_extension: python
add_wiki: true
email: mangham@gmail.com
github: Gaia-COB
project_description: Proposal management platform for Gaia Compact Object Binaries.
project_name: gaia-cob-pmp
python_version_primary: '3.11'
team: Sam Mangham
